### ISSUE TITLE
model.count is not a function

### ISSUE THREAD

**Issue by aravindnc** [chukaofili/sails-pager#1]
I'm getting this error while trying sails-pager.

Unhandled rejection TypeError: model.count is not a function

Here is my controller:
module.exports = {
	list: function (req, res) {
        var perPage = req.query.per_page;
        var currentPage = req.query.page;
        var conditions = {active: 1};
        pager.paginate('FileMaster', conditions, currentPage, perPage, false, 'createdAt DESC', function(err, records){
            if(err){
                res.send(err);
            }
            res.send(records);
        });
        
    },
};

**Comment by chukaofili** [comment]
Hello @aravindnc,

Looking at your code, it seems you are passing a string to the service instead of the model instance. Pass in **FileMaster** instead of **'FileMaster'**
`pager.paginate(FileMaster, conditions, currentPage, perPage, false, 'createdAt DESC', function(err, records)`
