### ISSUE TITLE
Pass Query String

### ISSUE THREAD

**Issue by rishab-yumist** [chukaofili/sails-pager#2]
Hey @chukaofili 

```
pager.paginate(OrgUnitRelationship, queryString , input.currentPage, input.perPage, [], 'createdAt', function(err, records) {
      console.log("pager getOrgs err: ", err, " result: ", records)
      if (!Utils.isEmpty(err)) {
        return cb({
          'statusCode': 200,
          'errorMessage': "Error retrieving Orgs."
        });
      }

      return cb(null, records);
    });
```

I want to pass queryString as an sql query

"eg: select  o.*, u.id from `order` o join `user` u on o.`user_id` = u.`id`"

How can I do that?

**Comment by chukaofili** [comment]
@rishab-yumist Sorry it took a while to respond here, didn't get a ping. As for your issue, it only accepts valid sailsjs  [(query language)](http://sailsjs.com/documentation/concepts/models-and-orm/query-language) and not native MySQL/MongoDB. I'll be happy to accept a PR to extend it :).
